### ISSUE TITLE
Bossfight Wannacry does not detonate

### ISSUE THREAD

**Issue by RamV2810** [HuskyHacks/PMAT-labs#12]
It was detonating just fine in the VM. However, now it does not detonate anymore. Not sure what went wrong; anybody else face this issue?

How to resolve?

**Comment by RamV2810** [comment]
I arm it and run it. But nothing happens.

**Comment by HuskyHacks** [comment]
Hi @RamV2810. We have a FAQ section on the course Discord server that addresses this issue specifically.

Closing.
