### ISSUE TITLE
Wannacry 

### ISSUE THREAD

**Issue by MasoomEXE** [HuskyHacks/PMAT-labs#19]
I tried running the wannacry.exe file .. unfortunately it won't run , the ransomware program isn't working i assume ..i waited for like 20mins..kept trying.. could you help me with that?? ..i unzipped using 7z and then renamed it to ".exe" ..and "run as administrator"

**Comment by HuskyHacks** [comment]
Sample works as intended. Please see the note above the video in the course on Wannacry.
