### ISSUE TITLE
Malware.Unknown.exe Not Sending Request For favicon.ico

### ISSUE THREAD

**Issue by x86Cow** [HuskyHacks/PMAT-labs#3]
I recently bought this course on TCM Security and when using wireshark to scan the network for favicon.ico using the http request full uri filter nothing comes through. any other traffic I send on windows manually comes through though.

recreation:
Run the program
check wireshark

**Comment by HuskyHacks** [comment]
Hello, thank you for opening this issue. All samples in the course were checked and confirmed to work as intended as recently as last week. If you can't find the expected IOCs, make sure to check your tool configs and your analysis methodology. Closing.
